### ISSUE TITLE
Interface Builder support

### ISSUE THREAD

**Issue by getaaron** [marzapower/MPNumericTextField#1]
I'd love to see storyboard support for this control using `IBInspectable`, `IB_DESIGNABLE`, etc. ([Details here](https://developer.apple.com/library/mac/recipes/xcode_help-IB_objects_media/chapters/CreatingaLiveViewofaCustomObject.html) if you're unfamiliar.)

**Comment by marzapower** [comment]
This would be an interesting feature. Adding the `IB_DESIGNABLE` keyword is straightforward. Adding `IBInspectable` params is not, since the main key features are handle via an `enum MPNumericTextFieldType`, a `NSLocale` and an `NSNumber`. While it's easy to find a work-around for the latter, the first two are not handled by Interface Builder. There should be too many work-arounds to make these modifications suitable for designing such a text field directly in IB.

**Comment by getaaron** [comment]
Yeah, I guess `IBInspectable` would require some [ugly hacks](http://stackoverflow.com/a/27435318/1445366), and without them `IB_DESIGNABLE` would be mostly pointless, so it's not really worth it.

**Comment by marzapower** [comment]
Yeah exactly. The only feasible way would be exposing the number as a float
and setting the default editing type as currency, just to be able to see
something. But I'd prefer leaving the defaul type as decimal.

Il sabato 28 febbraio 2015, Aaron Brager notifications@github.com ha
scritto:

> Closed #1 https://github.com/marzapower/MPNumericTextField/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marzapower/MPNumericTextField/issues/1#event-243665402
> .

## 

Ing. Daniele Di Bernardo
